Output stackql.gif

Set FontSize 15
Set Height 600
Set Width 1200
Set TypingSpeed 40ms
Set PlaybackSpeed 0.5
Set Framerate 30
Set Shell bash

Type "stackql --colorscheme=null shell"
Sleep 1s
Enter
Sleep 500ms

Type "show providers;"
Sleep 500ms
Enter
Sleep 4s

Type "show services in google;"
Sleep 500ms
Enter
Sleep 4s

Type "describe google.compute.instances;"
Sleep 500ms
Enter
Sleep 4s

Type "show methods in google.compute.instances;"
Sleep 500ms
Enter
Sleep 15s
